#!/bin/sh

RESET='\033[97m'
CYAN='\033[94m'
YELLOW='\033[93m'

printf "
${CYAN}    ___     ${YELLOW}%s${RESET}@${YELLOW}%s${RESET}
${CYAN}   (${RESET}.. ${CYAN}|    ${YELLOW}os:${RESET} %s
${CYAN}   (${YELLOW}<> ${CYAN}|    ${YELLOW}shell:${RESET} %s
${CYAN}  / ${RESET}__ ${CYAN} \\   ${YELLOW}pkgs:${RESET} %s
${CYAN} ( ${RESET}/  \\ ${CYAN}/|  ${YELLOW}uptime:${RESET} %s
${CYAN}_/\\ ${RESET}__)${CYAN}/_)  ${YELLOW}memory:${RESET} %s
${YELLOW}\\/${CYAN}_____${YELLOW}\\/   ${YELLOW}kernel:${RESET} %s
${RESET}
" \
"$USER" \
"$(hostname)" \
"$(. /etc/os-release; printf '%s' "${PRETTY_NAME:-Linux}")" \
"$SHELL" \
"$(ls -1 /var/db/ports 2>/dev/null | wc -l)" \
"$(awk '{printf "%d", $1/60}' /proc/uptime)" \
"$(free -m | awk 'NR==2 {printf "%d/%d", $3, $2}')" \
"$(uname -r)"
